# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: "Open Editions BootCamp"
site_description: ""
site_author: "Karina Varela"
repo_url: https://github.com/kmacedovarela/open-editions-bootcamp
edit_uri: ""
extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: en
  - markdownextradata: {}
  - awesome-pages: #https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
      collapse_single_pages: true
  - enumerate-headings: # https://github.com/timvink/mkdocs-enumerate-headings-plugin
      toc_depth: 3
      strict: true
      increment_across_pages: true
      exclude:
        - index.md
        - guides/index.md
#        - more.md
#        - README.md
  - git-revision-date-localized:
      type: iso_date
  - with-pdf:
        author: IBM


extra:
  product: 
    name: "IBM Business Automation Open Edition 9.0"
    legacy: "IBM Business Automation Open Edition 8.0"
    short: "IBAMOE"
    dm: "Decision Manager"
    pam: "Process Automation Manager"
    version: "9.0"
    versionLegacy: "8.0.4"
    maven: "Red Hat Maven General Access Repository"
    legacymaven: "Red Hat Maven General Access Repository"
    legacygav: "7.67.2.Final-redhat-00006"
    gav: "7.67.2.Final-redhat-00006"
    kogitogav: "f"
    kogitoplugin: "2.16.7.Final"
    sandbox: "KIE Sandbox"
    canvas: "IBM Business Automation Manager Canvas"
    extended: "Extended Services"
    workspace: "quick-kogito"
    bamAdmin: "bamAdmin"
    bamPass: "ibmpam1!"
    runner: "DMN Runner"
  sandbox:
    experimental: "https://kiegroup.github.io/kogito-online-staging/kie-sandbox-accelerators/#/"
    production: "http://localhost:9090/#"
  generator: false

theme:
  name: material
  locale: en
  navigation_depth: 1
  generator: false
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
        primary: light-blue
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - navigation.tabs.sticky
    - navigation.prune
    - toc.follow
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.tooltips

markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - attr_list
  - pymdownx.snippets

